
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BACK PLAY SKIP STOP VALUE VOLUMEcommand : STOPcommand : PLAYcommand : SKIPcommand : BACKcommand : VOLUME VALUE'
    
_lr_action_items = {'STOP':([0,],[2,]),'PLAY':([0,],[3,]),'SKIP':([0,],[4,]),'BACK':([0,],[5,]),'VOLUME':([0,],[6,]),'$end':([1,2,3,4,5,7,],[0,-1,-2,-3,-4,-5,]),'VALUE':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> STOP','command',1,'p_stop','projekt.py',67),
  ('command -> PLAY','command',1,'p_play','projekt.py',72),
  ('command -> SKIP','command',1,'p_skip','projekt.py',77),
  ('command -> BACK','command',1,'p_back','projekt.py',82),
  ('command -> VOLUME VALUE','command',2,'p_volume','projekt.py',87),
]
